# Generated by Django 4.1.2 on 2022-10-29 00:24

import bookings.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('duration', models.DurationField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type', models.CharField(choices=[('ACU_JP', 'Japanese acupuncture'), ('ACU_SHA', 'Non-insertive (Shakuju Therapy) acupuncture'), ('ACU_AUR', 'Auricular acupuncture'), ('STR', 'Stretching'), ('ESSOIL', 'Essential oils'), ('MIND', 'Mindfulness'), ('FITNESS', 'Fitness consultations'), ('DIETARY', 'Dietary consultations'), ('MOXI', 'Moxibustion'), ('TUINA', 'Tui na'), ('GUASHA', 'Gua sha'), ('REIKI', 'Reiki'), ('CUPPING', 'Cupping')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5, 'MAX!')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=255)),
                ('service_description', models.TextField(max_length=1000)),
                ('service_duration', models.DurationField()),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('service_type', models.CharField(choices=[('ACU_JP', 'Japanese acupuncture'), ('ACU_SHA', 'Non-insertive (Shakuju Therapy) acupuncture'), ('ACU_AUR', 'Auricular acupuncture'), ('STR', 'Stretching'), ('ESSOIL', 'Essential oils'), ('MIND', 'Mindfulness'), ('FITNESS', 'Fitness consultations'), ('DIETARY', 'Dietary consultations'), ('MOXI', 'Moxibustion'), ('TUINA', 'Tui na'), ('GUASHA', 'Gua sha'), ('REIKI', 'Reiki'), ('CUPPING', 'Cupping')], max_length=255)),
                ('date', models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 10, 29, 0, 24, 27, 426707, tzinfo=datetime.timezone(datetime.timedelta(0), 'UTC')))])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELED_BY_CUSTOMER', 'Canceled by customer'), ('CANCELED_BY_USER', 'Canceled by user')], default=bookings.models.AppointmentStatus['PENDING'], max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
